// @senticor/app-bff-contracts — die EINE Quelle der BFF-Wire-Verträge: TypeBox-Schemas
// (Validation + Static-Typen), Fehler-Envelope und OpenAPI-Metadaten. Bewusst ohne
// Fastify-Abhängigkeit — Server (app-bff-fastify) und künftige Clients teilen dieselben
// Formen.
export { ErrorEnvelopeSchema, type ErrorEnvelope } from "./error.js";
export {
  CapabilitiesDtoSchema,
  SessionDtoSchema,
  type CapabilitiesDto,
  type SessionDto,
} from "./session.js";
export {
  AccessibilityPreferencesSchema,
  ColorSchemeSchema,
  NavigationPreferencesSchema,
  UserPreferencesDtoSchema,
  UserPreferencesUpdateSchema,
  type UserPreferencesDto,
  type UserPreferencesUpdateDto,
} from "./preferences.js";
export {
  MailboxBoxSchema,
  MailboxCreateRequestSchema,
  MailboxListDtoSchema,
  MailboxListQuerySchema,
  MailboxMessageDtoSchema,
  MailboxMessageStatusSchema,
  MailboxScopeSchema,
  type MailboxCreateRequestDto,
  type MailboxListDto,
  type MailboxListQueryDto,
  type MailboxMessageDto,
} from "./mailbox.js";
export {
  CaseAllowedActionDtoSchema,
  CaseAllowedActionsDtoSchema,
  CaseApprovalRequestSchema,
  CaseApprovalResultDtoSchema,
  CaseAuditChainReportSchema,
  CaseAuditEventDtoSchema,
  CaseAuditListDtoSchema,
  CaseAuditQuerySchema,
  CaseCreateRequestSchema,
  CaseDtoSchema,
  CaseErasureRequestSchema,
  CaseErasureResultDtoSchema,
  RechtsbehelfAusgangSchema,
  RechtsbehelfEntscheidungRequestSchema,
  RechtsbehelfEntscheidungDtoSchema,
  LegalHoldRequestSchema,
  LegalHoldDtoSchema,
  CaseIdParamsSchema,
  CaseListDtoSchema,
  CaseListQuerySchema,
  CaseTransitionRequestSchema,
  ProcedureListDtoSchema,
  ProcedureSummaryDtoSchema,
  type CaseAllowedActionDto,
  type CaseAllowedActionsDto,
  type CaseApprovalRequestDto,
  type CaseApprovalResultDto,
  type CaseAuditChainReport,
  type ProcedureListDto,
  type ProcedureSummaryDto,
  type CaseAuditEventDto,
  type CaseAuditListDto,
  type CaseAuditQueryDto,
  type CaseCreateRequestDto,
  type CaseDto,
  type CaseErasureRequestDto,
  type CaseErasureResultDto,
  type RechtsbehelfAusgang,
  type RechtsbehelfEntscheidungRequestDto,
  type RechtsbehelfEntscheidungDto,
  type LegalHoldRequestDto,
  type LegalHoldDto,
  type CaseIdParamsDto,
  type CaseListDto,
  type CaseListQueryDto,
  type CaseTransitionRequestDto,
} from "./cases.js";
export {
  ProgressDtoSchema,
  TaskCreateRequestSchema,
  TaskDtoSchema,
  TaskIdParamsSchema,
  TaskListDtoSchema,
  TaskListQuerySchema,
  TaskPatchRequestSchema,
  TaskStateSchema,
  type ProgressDto,
  type TaskCreateRequestDto,
  type TaskDto,
  type TaskIdParamsDto,
  type TaskListDto,
  type TaskListQueryDto,
  type TaskPatchRequestDto,
  type TaskStateDto,
} from "./tasks.js";
export {
  AntragDtoSchema,
  AntragEinreichenRequestSchema,
  AntragIdParamsSchema,
  AntragListDtoSchema,
  RechtsbehelfArtSchema,
  RechtsbehelfDtoSchema,
  VerwaltungsaktDtoSchema,
  WiderspruchDtoSchema,
  WiderspruchRequestSchema,
  type AntragDto,
  type AntragEinreichenRequestDto,
  type AntragIdParamsDto,
  type AntragListDto,
  type VerwaltungsaktDto,
  type WiderspruchDto,
  type WiderspruchRequestDto,
} from "./buerger.js";
export {
  AiAssistClassSchema,
  AiAssistRequestSchema,
  AiSuggestionDtoSchema,
  type AiAssistRequestDto,
  type AiSuggestionDto,
} from "./ai-assist.js";
export {
  PaymentCreateRequestSchema,
  PaymentStatusDtoSchema,
  type PaymentCreateRequestDto,
  type PaymentStatusDto,
} from "./payment.js";
export {
  IdentityProfileDtoSchema,
  AssuranceRequestSchema,
  AssuranceResultDtoSchema,
  type IdentityProfileDto,
  type AssuranceRequestDto,
  type AssuranceResultDto,
} from "./identity.js";
export {
  AttachmentRefSchema,
  BescheidVersandRequestSchema,
  ZustellQuittungDtoSchema,
  ZustellStatusDtoSchema,
  type BescheidVersandRequestDto,
  type ZustellQuittungDto,
  type ZustellStatusDto,
} from "./zustellung.js";
export {
  EvidenceRequestDtoSchema,
  EvidenceRecordDtoSchema,
  type EvidenceRequestDto,
  type EvidenceRecordDto,
} from "./register.js";
export {
  KiVermerkRequestSchema,
  VermerkDtoSchema,
  VermerkIdParamsSchema,
  VermerkKindSchema,
  VermerkListDtoSchema,
  VermerkQuelleSchema,
  VermerkRequestSchema,
  VermerkReviewRequestSchema,
  VermerkReviewStatusSchema,
  VermerkSichtbarkeitSchema,
  WissenEintragDtoSchema,
  WissenExportDtoSchema,
  type KiVermerkRequestDto,
  type VermerkDto,
  type VermerkIdParamsDto,
  type VermerkKind,
  type VermerkListDto,
  type VermerkRequestDto,
  type VermerkReviewRequestDto,
  type WissenEintragDto,
  type WissenExportDto,
} from "./vermerke.js";
export {
  NachweisDownloadDtoSchema,
  NachweisIdParamsSchema,
  NachweisListDtoSchema,
  NachweisRefDtoSchema,
  NachweisUploadRequestSchema,
  type NachweisDownloadDto,
  type NachweisIdParamsDto,
  type NachweisListDto,
  type NachweisRefDto,
  type NachweisUploadRequestDto,
} from "./nachweise.js";
export {
  KiWissenRequestSchema,
  VerfahrenWissenEintragParamsSchema,
  VerfahrenWissenParamsSchema,
  WissenEintragRequestSchema,
  WissenExportEintragSchema,
  WissenReviewRequestSchema,
  WissenVerfahrenExportDtoSchema,
  WissenViewDtoSchema,
  WissenViewListDtoSchema,
  type KiWissenRequestDto,
  type VerfahrenWissenEintragParamsDto,
  type VerfahrenWissenParamsDto,
  type WissenEintragRequestDto,
  type WissenExportEintragDto,
  type WissenReviewRequestDto,
  type WissenVerfahrenExportDto,
  type WissenViewDto,
  type WissenViewListDto,
} from "./verfahren-wissen.js";
export { openApiInfo, openApiTags } from "./openapi.js";
