// @senticor/app-bff-contracts — die EINE Quelle der BFF-Wire-Verträge: TypeBox-Schemas
// (Validation + Static-Typen), Fehler-Envelope und OpenAPI-Metadaten. Bewusst ohne
// Fastify-Abhängigkeit — Server (app-bff-fastify) und künftige Clients teilen dieselben
// Formen.
export { ErrorEnvelopeSchema, type ErrorEnvelope } from "./error.js";
export {
  CapabilitiesDtoSchema,
  SessionDtoSchema,
  type CapabilitiesDto,
  type SessionDto,
} from "./session.js";
export {
  AccessibilityPreferencesSchema,
  ColorSchemeSchema,
  NavigationPreferencesSchema,
  UserPreferencesDtoSchema,
  UserPreferencesUpdateSchema,
  type UserPreferencesDto,
  type UserPreferencesUpdateDto,
} from "./preferences.js";
export {
  MailboxBoxSchema,
  MailboxCreateRequestSchema,
  MailboxListDtoSchema,
  MailboxListQuerySchema,
  MailboxMessageDtoSchema,
  MailboxMessageStatusSchema,
  MailboxScopeSchema,
  type MailboxCreateRequestDto,
  type MailboxListDto,
  type MailboxListQueryDto,
  type MailboxMessageDto,
} from "./mailbox.js";
export {
  CaseAllowedActionDtoSchema,
  CaseAllowedActionsDtoSchema,
  CaseAuditEventDtoSchema,
  CaseAuditListDtoSchema,
  CaseAuditQuerySchema,
  CaseCreateRequestSchema,
  CaseDtoSchema,
  CaseIdParamsSchema,
  CaseListDtoSchema,
  CaseListQuerySchema,
  CaseTransitionRequestSchema,
  ProcedureListDtoSchema,
  ProcedureSummaryDtoSchema,
  type CaseAllowedActionDto,
  type CaseAllowedActionsDto,
  type ProcedureListDto,
  type ProcedureSummaryDto,
  type CaseAuditEventDto,
  type CaseAuditListDto,
  type CaseAuditQueryDto,
  type CaseCreateRequestDto,
  type CaseDto,
  type CaseIdParamsDto,
  type CaseListDto,
  type CaseListQueryDto,
  type CaseTransitionRequestDto,
} from "./cases.js";
export {
  ProgressDtoSchema,
  TaskCreateRequestSchema,
  TaskDtoSchema,
  TaskIdParamsSchema,
  TaskListDtoSchema,
  TaskListQuerySchema,
  TaskPatchRequestSchema,
  TaskStateSchema,
  type ProgressDto,
  type TaskCreateRequestDto,
  type TaskDto,
  type TaskIdParamsDto,
  type TaskListDto,
  type TaskListQueryDto,
  type TaskPatchRequestDto,
  type TaskStateDto,
} from "./tasks.js";
export {
  AntragDtoSchema,
  AntragEinreichenRequestSchema,
  AntragIdParamsSchema,
  AntragListDtoSchema,
  RechtsbehelfArtSchema,
  RechtsbehelfDtoSchema,
  VerwaltungsaktDtoSchema,
  WiderspruchDtoSchema,
  WiderspruchRequestSchema,
  type AntragDto,
  type AntragEinreichenRequestDto,
  type AntragIdParamsDto,
  type AntragListDto,
  type VerwaltungsaktDto,
  type WiderspruchDto,
  type WiderspruchRequestDto,
} from "./buerger.js";
export {
  AiAssistClassSchema,
  AiAssistRequestSchema,
  AiSuggestionDtoSchema,
  type AiAssistRequestDto,
  type AiSuggestionDto,
} from "./ai-assist.js";
export { openApiInfo, openApiTags } from "./openapi.js";
