apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fachverfahren-web
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fachverfahren-template
      app.kubernetes.io/component: web
